version: "3"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: butter_user
      POSTGRES_PASSWORD: butter_password
      POSTGRES_DB: butter_db
  butter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgres://butter_user:butter_password@database/butter_db"
    ports:
      - "8000:8000"
    entrypoint: ./docker-entrypoint.sh
    depends_on:
      - database