version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
  butter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: "QWErty#@!"
      DATABASE_URL: "postgres://art_user:art_password@database/art_backend"
    ports:
      - "8000:8000"
    entrypoint: ./docker-entry.sh
    depends_on:
      - database