# Generated by Django 2.2.6 on 2020-01-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertermsagreement',
            old_name='user',
            new_name='signed_user',
        ),
    ]
